### ISSUE TITLE
Issue with recipe DFUBlaster.munki

### ISSUE THREAD

**Issue by jpiel** [autopkg/kevinmcox-recipes#4]
I receive the following error when using the recipe : 
`Errno 18] Cross-device link: '/Volumes/4DSrv-CacheVD/AutoPkg/Cache/local.munki.DFUBlaster/downloads/PreBeta-DFU_Blaster_Build-2108_Version-2.1.dmg' -> 'DFU_Blaster.dmg'`

I guess this comes from the FileMover Processor.
adding %RECIPE_CACHE_DIR%/ to the target should fix the issue. (and adding it to the pkg_path of the MunkiImporter processor too)

**Comment by kevinmcox** [comment]
Good catch @jpiel, thank you. It worked in my testing, but I see why I just got lucky to not hit this error.
