### ISSUE TITLE
DFU Blaster

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/kevinmcox-recipes#7]
Hey, @kevinmcox 

We're seeing an error when using this recipe with the Virus Total post processor. 

```
Processor: io.github.hjuutilainen.VirusTotalAnalyzer/VirusTotalAnalyzer: Error: [Errno 2] No such file or directory: '/Users/sadmin/Library/AutoPkg/Cache/local.definition.DFUBlaster/downloads/PreBeta-DFU_Blaster_Build-2112_Version-2.2.dmg'
```

The Virus Total processor uploads `%pathname%` which has been moved: https://github.com/autopkg/kevinmcox-recipes/blob/master/Twocanoes%20Software/DFUBlaster.munki.recipe#L114#L124 

Is this step needed? If you need the dmg in a specific location, would `Copier` work for you? 

Thanks!

**Comment by kevinmcox** [comment]
@paul-cossey let me take a look and see if I can remember what I was doing last year.

**Comment by kevinmcox** [comment]
@paul-cossey Ah I remember now. The downloaded file is named `PreBeta-DFU_Blaster_Build-2112_Version-2.2.dmg` so I'm using `FileMover` to rename the DMG to something more succinct in `DFU_Blaster.dmg` before importing it into Munki.

**Comment by paul-cossey** [comment]
Gotcha, so instead of `FileMover` you could add `filename` to `URLDownloader` and achieve the same result?

```
<dict>
    <key>Arguments</key>
    <dict>
        <key>filename</key>
        <string>%NAME%.dmg</string>
        <key>url</key>
        <string>https://bitbucket.org%match%</string>
    </dict>
    <key>Processor</key>
    <string>URLDownloader</string>
</dict>
```

**Comment by kevinmcox** [comment]
Yep, great solution. Give me a few minutes to fix things up.

**Comment by paul-cossey** [comment]
Awesome! Thank you! 😄
